version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.env
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  test:
    build:
      context: .
      dockerfile: Dockerfile.env
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test:unit']
